=== oscar-cluster/pkgsrc/libv3m-v2m/tags/0.9.1/test/profile_data/profiles.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
DTD for KVMs profiles.
-->

<!ELEMENT profiles (profile*)>

<!ELEMENT profile (name, type, image, nic1, nic2) >

<!ELEMENT name (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT image (#PCDATA)>

<!ELEMENT nic1 (type, mac)>

<!ELEMENT nic2 (type, mac)>

<!ELEMENT mac (#PCDATA)>

=== oscar-cluster/pkgsrc/libv3m-v2m/tags/0.9.1/test/profile_data/profiles.xml
<?xml version="1.0"?>
<!DOCTYPE profiles PUBLIC "" "profiles.dtd">
<profiles>
	<profile>
		<name>test1</name>
		<type>test2</type>
		<image>test3</image>
		<nic1>
			<type>TUN/TAP</type>
			<mac>00:01:02:03:04:05</mac>
		</nic1>
		<nic2>
			<type>VLAN</type>
			<mac>00:01:02:03:04:06</mac>
		</nic2>
	</profile>
</profiles>
