=== oscar-cluster/pkgsrc/libv3m-v2m/tags/0.9.2/dtd/v3m_profile.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
DTD for V2M profiles.
-->

<!ELEMENT profile (name, type, memory?, image, virtual_disks?, cdrom?, nic1?, nic2?) >

<!ELEMENT name (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT image (#PCDATA)>
<!ATTLIST image size CDATA #IMPLIED>

<!ELEMENT memory (#PCDATA)>

<!ELEMENT virtual_disks (virtual_disk+)>
<!ELEMENT virtual_disk (#PCDATA)>
<!ATTLIST virtual_disk id CDATA #REQUIRED>

<!ELEMENT cdrom (#PCDATA)>

<!ELEMENT nic1 (type, mac)>

<!ELEMENT nic2 (type, mac)>

<!ELEMENT mac (#PCDATA)>

=== oscar-cluster/pkgsrc/libv3m-v2m/tools/v2m/branches/1.0/testing/qemu_bootable_cdrom_test.xml
<?xml version="1.0"?>
<!DOCTYPE profile PUBLIC "" "/etc/v3m/v3m_profile.dtd">
<profile>
	<name>QEMUTest</name>
	<type>Qemu</type>
	<image size="1000">./qemu_test.img</image>
    <cdrom>../contrib/bin/oscar_bootcd.iso</cdrom>
	<nic1>
		<type>TUN/TAP</type>
		<mac>00:02:c3:c4:c5:c6</mac>
	</nic1>
	<nic2>
		<type>VLAN</type>
		<mac>00:02:c3:04:b1:aa</mac>
	</nic2>
</profile>

=== oscar-cluster/pkgsrc/libv3m-v2m/tags/0.9.1/doc/example_profile_qemu.xml
<?xml version="1.0"?>
<!DOCTYPE profile PUBLIC "" "v3m_profile.dtd">
<profile>
	<name>krg1</name>
	<type>Qemu</type>
	<image size="500">/home/gvallee/temp/v2m/test.img</image>
	<cdrom>/dev/hdc</cdrom>
	<nic1>
		<type>TUN/TAP</type>
		<mac>00:01:02:03:04:05</mac>
	</nic1>
	<nic2>
		<type>VLAN</type>
		<mac>00:0A:03:04:05:0A</mac>
	</nic2>
</profile>

=== oscar-cluster/pkgsrc/libv3m-v2m/branches/1.0/test/profile_data/profiles.xml
<?xml version="1.0"?>
<!DOCTYPE profile PUBLIC "" "/etc/libv3m/v3m_profile.dtd">
	<profile>
		<name>test1</name>
		<type>test2</type>
		<image>test3</image>
		<nic1>
			<type>TUN/TAP</type>
			<mac>00:01:02:03:04:05</mac>
		</nic1>
		<nic2>
			<type>VLAN</type>
			<mac>00:01:02:03:04:06</mac>
		</nic2>
	</profile>

=== oscar-cluster/pkgsrc/libv3m-v2m/tools/v2m/trunk/testing/qemu_test.xml
<?xml version="1.0"?>
<!DOCTYPE profile PUBLIC "" "/etc/v3m/v3m_profile.dtd">
<profile>
	<name>QEMUTest</name>
	<type>Qemu</type>
	<image size="1000">./linux.img</image>
	<nic1>
		<type>TUN/TAP</type>
		<mac>00:02:c3:c4:c5:c6</mac>
	</nic1>
	<nic2>
		<type>VLAN</type>
		<mac>00:02:c3:04:b1:aa</mac>
	</nic2>
</profile>
